server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: driver-msv
              uri: lb://DRIVER-MSV
              predicates:
                - Path=/api/drivers/**
              

            - id: order-msv
              uri: lb://ORDER-MSV
              predicates:
                - Path=/api/orders/**
          